Improved the init.d script to use /etc/default/calabard to grab optional variables and to provide working stop, status and try-restart options

diff --git a/scripts/calabard b/scripts/calabard
--- a/scripts/calabard
+++ b/scripts/calabard
@@ -1,50 +1,132 @@
-#!/bin/sh
+#! /bin/sh
 
-USER=root
-NAME=calabard
-VIRTUALENV=%(virtualenv_dir)s
-DAEMON=$VIRTUALENV/bin/$NAME
-PIDFILE=/var/run/$NAME.pid
-LOGFILE=/var/log/calabar/$NAME.log
-ERR_LOGFILE=/var/log/calabar/$NAME_err.log
+### BEGIN INIT INFO
+# Provides:		calabard
+# Required-Start:
+# Required-Stop:
+# Default-Start:	2 3 4 5
+# Default-Stop:		1
+# Short-Description:	calabar vpn tunnel manager daemon
+### END INIT INFO
 
-[ -x "$DAEMON" ] || echo "Daemon not found at $DAEMON"
-[ -x "$DAEMON" ] || exit 0
+set -e
 
-#
-# Function that stops the daemon/service
-#
-do_stop()
-{
-        # Return
-        #   0 if daemon has been stopped
-        #   1 if daemon was already stopped
-        #   2 if daemon could not be stopped
-        #   other if a failure occurred
-        start-stop-daemon --stop --retry 10 --pidfile $PIDFILE --name $NAME --user $USER
-        rm -f $PIDFILE
+VIRTUALENV=''
+CALABARD_PID_FILE="/var/run/calabard.pid"
+CALABARD_LOG_FILE="/var/log/calabard.log"
+CALABARD="calabard"
+
+if test -f /etc/default/calabard; then
+    . /etc/default/calabard
+fi
+
+
+. /lib/lsb/init-functions
+CALABARD_OPTS="--logfile $CALABARD_LOG_FILE --daemon"
+
+if [ -n "$2" ]; then
+    CALABARD_OPTS="$2 $CALABARD_OPTS"
+fi
+
+# Are we running from init?
+run_by_init() {
+    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
 }
 
+
+check_dev_null() {
+    if [ ! -c /dev/null ]; then
+	if [ "$1" = log_end_msg ]; then
+	    log_end_msg 1 || true
+	fi
+	if ! run_by_init; then
+	    log_action_msg "/dev/null is not a character device!"
+	fi
+	exit 1
+    fi
+}
+
+
+export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
+if [ ! -z "$VIRTUALENV" ]; then
+    . "$VIRTUALENV/bin/activate"
+    export PATH="$VIRTUALENV/bin:$PATH"
+    CALABARD="$VIRTUALENV/bin/$CALABARD"
+fi
+
+# Normal calabard start
 do_start()
 {
-	start-stop-daemon --start --exec $DAEMON --name $NAME --pidfile $PIDFILE --background --make-pidfile --chuid $USER --user $USER -- --daemon > $LOGFILE &> $ERR_LOGFILE
+    if start-stop-daemon --start --quiet --oknodo \
+	    --pidfile $CALABARD_PID_FILE --make-pidfile --exec $CALABARD \
+	    -- $CALABARD_OPTS; then
+	log_end_msg 0
+    else
+	log_end_msg 1
+    fi
 }
 
 case "$1" in
   start)
-        echo "Stopping any running daemons..."
-        do_stop
-        echo "Starting $NAME..."
-        do_start
+	check_dev_null
+	log_daemon_msg "Starting calabar tunnel manager" "calabard"
+	do_start
 	;;
   stop)
-        echo "Stopping $NAME..."
-        do_stop
+	log_daemon_msg "Stopping calabar tunnel manager" "calabard"
+	if start-stop-daemon --stop --quiet --oknodo \
+		--pidfile $CALABARD_PID_FILE; then
+	    log_end_msg 0
+	else
+	    log_end_msg 1
+	fi
 	;;
+
+  reload|force-reload)
+    echo "Use start+stop"
+	;;
+
+  restart)
+	log_daemon_msg "Restarting calabar tunnel manager" "calabard"
+	start-stop-daemon --stop --quiet --oknodo --retry 30
+		--pidfile $CALABARD_PID_FILE
+	check_dev_null log_end_msg
+	do_start
+	;;
+
+  try-restart)
+	log_daemon_msg "Restarting calabar tunnel manager" "calabard"
+	set +e
+	    start-stop-daemon --stop --quiet --retry 30 \
+		    --pidfile $CALABARD_PID_FILE
+	RET="$?"
+	set -e
+	case $RET in
+	    0)
+		# old daemon stopped
+		check_dev_null log_end_msg
+		do_start
+		;;
+	    1)
+		# daemon not running
+		log_progress_msg "(not running)"
+		log_end_msg 0
+		;;
+	    *)
+		# failed to stop
+		log_progress_msg "(failed to stop)"
+		log_end_msg 1
+		;;
+	esac
+	;;
+
+  status)
+	status_of_proc -p $CALABARD_PID_FILE $CALABARD calabard && exit 0 || exit $?
+	;;
+
   *)
-	echo "Usage: $NAME {start|stop}" >&2
-	exit 3
-	;;
+	log_action_msg "Usage: /etc/init.d/calabard {start|stop|force-reload|restart|try-restart|status}"
+	exit 1
 esac
 
-:
+exit 0
